welp_mailchimp_webhook:
    resource: Welp\MailchimpBundle\Controller\WebhookController
    type:     annotation
    arguments:
        - '@welp_mailchimp.list_provider'
        - '@Symfony\Component\EventDispatcher\EventDispatcher'
